apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
data:
  DATABASE_URL: "postgres://postgres:password@postgres:5432/people"
  NODE_ENV: "development"
  VUE_APP_API_URL: "http://myapp-dev-backend-service:3000"
