apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-deployment-role
  namespace: dev
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["pods", "services", "deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
