apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - release-staging.yaml

configMapGenerator:
  - name: myapp-config
    literals:
      - DATABASE_URL=postgres://staging_user:staging_pass@staging-db:5432/people
      - NODE_ENV=staging
