apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: staging-deployment-role
  namespace: staging
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["pods", "services", "deployments", "replicasets", "endpoints", "endpointslices"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
