apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: staging-deployment-binding
  namespace: staging
subjects:
- kind: ServiceAccount
  name: cicd-service-account
  namespace: staging
roleRef:
  kind: Role
  name: staging-deployment-role
  apiGroup: rbac.authorization.k8s.io
